
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../football:/app   # monta la carpeta Symfony en /app
    ports:
      - "8000:8000"               # para acceder a la API en localhost:8000
    depends_on:
      - db
    command: php -S 0.0.0.0:8000 -t public

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: football
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
